#reference filters get applied to the map and to the icp
referenceDataPointsFilters:
  - MaxDistDataPointsFilter:
      maxDist: 30.0
  - RandomSamplingDataPointsFilter:
      prob: 0.3
  - SurfaceNormalDataPointsFilter:
      knn: 5
      epsilon: 0
      keepNormals: 1
      keepDensities: 1
  - ObservationDirectionDataPointsFilter
  - OrientNormalsDataPointsFilter 
matcher:
  KDTreeMatcher:
    knn: 1
    maxDist: 3.0
    epsilon: 3.16

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.65
  - SurfaceNormalOutlierFilter:
     maxAngle: 1.57

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 15
  - BoundTransformationChecker:
      maxRotationNorm: 0.8
      maxTranslationNorm: 30.00

inspector:
#  VTKFileInspector
  NullInspector

logger:
#  FileLogger
  NullLogger
